In [9]:
import piplite
await piplite.install('seaborn')

In [2]:
import numpy as np
import pandas as pd

In [103]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style ='font-family:"Courier New" Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [16]:
import seaborn as sns
from pyodide.http import open_url

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/planets.csv"
safe_data = open_url(url)
planets = pd.read_csv(safe_data)
print(planets.shape)

(1035, 6)

In [17]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [18]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [19]:
ser.sum()

np.float64(2.811925491708157)

In [20]:
ser.mean()

np.float64(0.5623850983416314)

In [23]:
df = pd.DataFrame({'A': rng.rand(5),
                  'B': rng.rand(5)})
df

          A         B
0  0.020584  0.183405
1  0.969910  0.304242
2  0.832443  0.524756
3  0.212339  0.431945
4  0.181825  0.291229

In [26]:
df = pd.DataFrame(rng.rand(5, 2), columns=list('AB'))
df

          A         B
0  0.122038  0.495177
1  0.034389  0.909320
2  0.258780  0.662522
3  0.311711  0.520068
4  0.546710  0.184854

In [27]:
df.mean()

A    0.254726
B    0.554388
dtype: float64

In [28]:
df.mean(axis='columns')

0    0.308608
1    0.471854
2    0.460651
3    0.415890
4    0.365782
dtype: float64

In [29]:
df.mean(axis=1)

0    0.308608
1    0.471854
2    0.460651
3    0.415890
4    0.365782
dtype: float64

In [30]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [40]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [41]:
df.groupby('key')

In [47]:
df.groupby('key').prod()

     data
key
A       0
B       4
C      10

In [48]:
planets.groupby('method')

In [49]:
planets.groupby('method')['orbital_period']

In [65]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [58]:
for method, group in planets.groupby('method'):
    print(f"{method:30s} shape={group.shape}")

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

In [63]:
planets.groupby('method')['year'].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,2011.500000,2.121320,2010.0,2010.75,2011.5,2012.25,2013.0
Eclipse Timing Variations,9.0,2010.000000,1.414214,2008.0,2009.00,2010.0,2011.00,2012.0
Imaging,38.0,2009.131579,2.781901,2004.0,2008.00,2009.0,2011.00,2013.0
Microlensing,23.0,2009.782609,2.859697,2004.0,2008.00,2010.0,2012.00,2013.0
Orbital Brightness Modulation,3.0,2011.666667,1.154701,2011.0,2011.00,2011.0,2012.00,2013.0
Pulsar Timing,5.0,1998.400000,8.384510,1992.0,1992.00,1994.0,2003.00,2011.0
Pulsation Timing Variations,1.0,2007.000000,NaN,2007.0,2007.00,2007.0,2007.00,2007.0
Radial Velocity,553.0,2007.518987,4.249052,1989.0,2005.00,2009.0,2011.00,2014.0
Transit,397.0,2011.236776,2.077867,2002.0,2010.00,2012.0,2013.00,2014.0
Transit Timing Variations,4.0,2012.500000,1.290994,2011.0,2011.75,2012.5,2013.25,2014.0

In [82]:
rng = np.random.RandomState(42)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                  columns=['key', 'data1', 'data2'])
df

  key  data1  data2
0   A      0      6
1   B      1      3
2   C      2      7
3   A      3      4
4   B      4      6
5   C      5      9

In [85]:
df.groupby('key').aggregate(['min', np.median, max])

<ipython-input-85-1925fa6293f4>:1: FutureWarning: The provided callable <function median at 0x48e48d0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('key').aggregate(['min', np.median, max])
<ipython-input-85-1925fa6293f4>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('key').aggregate(['min', np.median, max])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     4    5.0   6
B       1    2.5   4     3    4.5   6
C       2    3.5   5     7    8.0   9

In [91]:
df.groupby('key').aggregate({'data1':'min',
                             'data2': 'max'})

     data1  data2
key
A        0      6
B        1      6
C        2      9

In [104]:
def filter_func(x):
    return x['data2'].std() > 4

display('df', "df.groupby('key').std()", "df.groupby('key').filter(filter_func)")

df
  key  data1  data2
0   A      0      6
1   B      1      3
2   C      2      7
3   A      3      4
4   B      4      6
5   C      5      9

df.groupby('key').std()
       data1     data2
key
A    2.12132  1.414214
B    2.12132  2.121320
C    2.12132  1.414214

df.groupby('key').filter(filter_func)
Empty DataFrame
Columns: [key, data1, data2]
Index: []

In [105]:
df.groupby('key').transform(lambda x: x - x.mean())

   data1  data2
0   -1.5    1.0
1   -1.5   -1.5
2   -1.5   -1.0
3    1.5   -1.0
4    1.5    1.5
5    1.5    1.0

In [106]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

display('df', "df.groupby('key').apply(norm_by_data2)")

<string>:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
<string>:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

df
  key  data1  data2
0   A      0      6
1   B      1      3
2   C      2      7
3   A      3      4
4   B      4      6
5   C      5      9

df.groupby('key').apply(norm_by_data2)
      key     data1  data2
key
A   0   A  0.000000      6
    3   A  0.300000      4
B   1   B  0.111111      3
    4   B  0.444444      6
C   2   C  0.125000      7
    5   C  0.312500      9

In [107]:
L = [0, 1, 0, 1, 2, 0]
display('df', 'df.groupby(L).sum()')

df
  key  data1  data2
0   A      0      6
1   B      1      3
2   C      2      7
3   A      3      4
4   B      4      6
5   C      5      9

df.groupby(L).sum()
   key  data1  data2
0  ACC      7     22
1   BA      4      7
2    B      4      6

In [108]:
display('df', "df.groupby(df['key']).sum()")

df
  key  data1  data2
0   A      0      6
1   B      1      3
2   C      2      7
3   A      3      4
4   B      4      6
5   C      5      9

df.groupby(df['key']).sum()
     data1  data2
key
A        3     10
B        5      9
C        7     16

In [109]:
df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}
display('df2', 'df2.groupby(mapping).sum()')

df2
     data1  data2
key
A        0      6
B        1      3
C        2      7
A        3      4
B        4      6
C        5      9

df2.groupby(mapping).sum()
           data1  data2
key
consonant     12     25
vowel          3     10

In [110]:
display('df2', 'df2.groupby(str.lower).mean()')

df2
     data1  data2
key
A        0      6
B        1      3
C        2      7
A        3      4
B        4      6
C        5      9

df2.groupby(str.lower).mean()
     data1  data2
key
a      1.5    5.0
b      2.5    4.5
c      3.5    8.0

In [111]:
df2.groupby([str.lower, mapping]).mean()

               data1  data2
key key
a   vowel        1.5    5.0
b   consonant    2.5    4.5
c   consonant    3.5    8.0

In [112]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0