In [2]:
!mamba install numpy pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.867 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import numpy as  np
import pandas as pd

In [25]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [11]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [12]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [13]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [14]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [15]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [16]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='str')

In [17]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [8]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [27]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

    A  B
0   2  1
1  11  5

In [26]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

   B  A  C
0  6  9  2
1  6  7  4
2  3  7  7

In [28]:
A + B

      A     B   C
0  11.0   7.0 NaN
1  18.0  11.0 NaN
2   NaN   NaN NaN

In [29]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

       A      B      C
0  11.00   7.00   6.75
1  18.00  11.00   8.75
2  11.75   7.75  11.75

In [30]:
A = rng.randint(10, size=(3, 4))
A

array([[1, 4, 0, 9],
       [5, 8, 0, 9],
       [2, 6, 3, 8]])

In [31]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 4,  4,  0,  0],
       [ 1,  2,  3, -1]])

In [32]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1  4  4  0  0
2  1  2  3 -1

In [33]:
df.subtract(df['R'], axis=0)

   Q  R  S  T
0 -3  0 -4  5
1 -3  0 -8  1
2 -4  0 -3  2

In [34]:
df

   Q  R  S  T
0  1  4  0  9
1  5  8  0  9
2  2  6  3  8

In [35]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    0
Name: 0, dtype: int32

In [36]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN  0.0 NaN
2  1.0 NaN  3.0 NaN

In [43]:
halfrow_fill = halfrow.reindex(df.columns, fill_value=0)
halfrow_fill

Q    1
R    0
S    0
T    0
Name: 0, dtype: int32

In [44]:
df.subtract(halfrow_fill)

   Q  R  S  T
0  0  4  0  9
1  4  8  0  9
2  1  6  3  8